<a href="https://colab.research.google.com/github/radwaelreedy/ml-data-analysis/blob/main/multiple_linear_regressionAssignment_multiple_linear_regression_Boston.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
dt = pd.read_csv('/content/Boston.csv')

In [3]:
dt

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [4]:
dt = dt.drop('Unnamed: 0', axis=1)

In [5]:
dt

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [6]:
dt.shape

(506, 14)

In [7]:
X = dt.iloc[:,0:13].values
y=dt.iloc[:,13].values

In [8]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.4, random_state=42)

In [10]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
# sc = StandardScaler()
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
reg = linear_model.LinearRegression()

reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred =reg.predict(X_test)
y_pred

array([28.70025691, 37.27542414, 14.45066349, 25.73435643, 18.49763912,
       22.76561878, 17.11890368, 13.48208813, 22.54968769, 20.55427051,
       24.89964971, 17.95378789, -6.25387186, 21.45751485, 19.24359044,
       25.88484249, 20.03562327,  5.43649759, 40.51846823, 17.25804397,
       27.97547423, 30.52428232, 10.62579589, 24.13957256, 17.9691631 ,
       15.70456146, 23.13185264, 14.47022575, 22.38985994, 19.37080505,
       22.24020037, 25.33048308, 25.11428577, 18.622199  , 16.09804981,
       17.56608944, 30.84772682, 20.52366567, 24.21685764, 25.12389018,
       13.87545879, 32.08576418, 42.69334232, 17.57356292, 27.18664139,
       17.00879858, 13.65816821, 26.32678962, 19.85072475, 30.22451992,
       20.89326788, 34.32273159, 15.30429383, 26.09067695, 39.54965618,
       22.78325442, 18.64595069, 33.48386781, 24.94968103, 12.43100969,
       22.47035481, 30.85432505, 32.1854089 , 16.87897756, 20.67775641,
       16.56514522, 20.02974058, 26.41085611, 31.55334393, 12.01236966,
       20.5755039 , 27.2101929 , 10.84119438, 16.94886713, 23.819897  ,
        5.41829661, 21.34860257, 41.46811322, 17.89184792,  8.55598713,
       21.22643245, 12.55281823, 21.60873562,  9.23301292, 23.01327607,
       32.40354417, 18.838331  , 25.84079392, 29.68609136, 19.67664041,
       25.86395856,  5.77415108, 19.85173596, 14.85755383, 14.78530087,
       20.54331883, 24.79552215, -0.38128645, 13.86239885, 15.56058277,
       22.22723166, 24.50054142, 10.53570651, 19.94505871, 23.7931239 ,
       11.98747478, 18.6702269 , 25.90367796, 21.28160063, 24.63144222,
        7.57729972, 18.74553016, 22.18842892, 27.6454184 , 32.11389939,
       15.44169788, 34.29613564, 12.93746053, 21.31348928, 28.78086431,
       15.52254246, 24.96278456,  4.69457295, 23.80013757, 26.24973178,
       23.33054233, 25.28572597, 33.43479966, 21.26605693, 38.31882195,
       13.57250428, 25.35725719, 17.63235356, 20.24489731,  9.59365733,
       21.15392804, 22.76713792, 32.33731713, 31.76032874, 15.22252164,
       16.76008974, 29.08091493, 25.09803633, 16.78722207,  6.55837627,
       26.51952996, 23.64255121, 17.06446945, 13.06111281, 39.57174946,
       16.63358238, 18.06625285, 25.38864599, 23.58406741, 22.44180986,
       21.762737  , 16.71391675, 23.31074519, 29.09428383,  7.28647565,
       24.30936529, 17.1913895 , 21.18924966, 25.29277028, 28.17616874,
       20.74427938, 40.59250988, 18.6287946 , 15.12541523, 18.29850858,
       17.15651918, 22.43515912, 23.64679216, 33.40316974, 22.40547942,
       20.28211069, 25.2413554 , 31.47695469, 33.39153046, 28.43793741,
        8.541879  ,  4.85267978, 12.42580604, 20.41598522, 36.05885172,
       33.43770529, 15.81380686,  3.26964909, 33.70613701, 21.80595258,
       19.16226992, 26.12924528, 18.61875414, 17.76686204, 11.01275111,
       32.47158925, 24.70737227, 19.49374868, 19.3662591 , 11.5366082 ,
       28.982763  , 21.74478698, 32.57522994])

In [13]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.7125140936111223

In [14]:
reg.score(X_train, y_train)

0.747199884740759

In [15]:
a = reg.coef_
a

array([-10.09760831,   3.60978024,   0.79557132,   3.51131977,
        -7.0233589 ,  18.7108654 ,  -1.74346842, -16.38195487,
         5.81936946,  -5.253767  ,  -8.33224218,   4.27665681,
       -20.87126481])

In [16]:
b = reg.intercept_
b

np.float64(28.008173027118545)

In [17]:
y_pred1= a.dot(X_test.T)+b
y_pred1

array([28.70025691, 37.27542414, 14.45066349, 25.73435643, 18.49763912,
       22.76561878, 17.11890368, 13.48208813, 22.54968769, 20.55427051,
       24.89964971, 17.95378789, -6.25387186, 21.45751485, 19.24359044,
       25.88484249, 20.03562327,  5.43649759, 40.51846823, 17.25804397,
       27.97547423, 30.52428232, 10.62579589, 24.13957256, 17.9691631 ,
       15.70456146, 23.13185264, 14.47022575, 22.38985994, 19.37080505,
       22.24020037, 25.33048308, 25.11428577, 18.622199  , 16.09804981,
       17.56608944, 30.84772682, 20.52366567, 24.21685764, 25.12389018,
       13.87545879, 32.08576418, 42.69334232, 17.57356292, 27.18664139,
       17.00879858, 13.65816821, 26.32678962, 19.85072475, 30.22451992,
       20.89326788, 34.32273159, 15.30429383, 26.09067695, 39.54965618,
       22.78325442, 18.64595069, 33.48386781, 24.94968103, 12.43100969,
       22.47035481, 30.85432505, 32.1854089 , 16.87897756, 20.67775641,
       16.56514522, 20.02974058, 26.41085611, 31.55334393, 12.01236966,
       20.5755039 , 27.2101929 , 10.84119438, 16.94886713, 23.819897  ,
        5.41829661, 21.34860257, 41.46811322, 17.89184792,  8.55598713,
       21.22643245, 12.55281823, 21.60873562,  9.23301292, 23.01327607,
       32.40354417, 18.838331  , 25.84079392, 29.68609136, 19.67664041,
       25.86395856,  5.77415108, 19.85173596, 14.85755383, 14.78530087,
       20.54331883, 24.79552215, -0.38128645, 13.86239885, 15.56058277,
       22.22723166, 24.50054142, 10.53570651, 19.94505871, 23.7931239 ,
       11.98747478, 18.6702269 , 25.90367796, 21.28160063, 24.63144222,
        7.57729972, 18.74553016, 22.18842892, 27.6454184 , 32.11389939,
       15.44169788, 34.29613564, 12.93746053, 21.31348928, 28.78086431,
       15.52254246, 24.96278456,  4.69457295, 23.80013757, 26.24973178,
       23.33054233, 25.28572597, 33.43479966, 21.26605693, 38.31882195,
       13.57250428, 25.35725719, 17.63235356, 20.24489731,  9.59365733,
       21.15392804, 22.76713792, 32.33731713, 31.76032874, 15.22252164,
       16.76008974, 29.08091493, 25.09803633, 16.78722207,  6.55837627,
       26.51952996, 23.64255121, 17.06446945, 13.06111281, 39.57174946,
       16.63358238, 18.06625285, 25.38864599, 23.58406741, 22.44180986,
       21.762737  , 16.71391675, 23.31074519, 29.09428383,  7.28647565,
       24.30936529, 17.1913895 , 21.18924966, 25.29277028, 28.17616874,
       20.74427938, 40.59250988, 18.6287946 , 15.12541523, 18.29850858,
       17.15651918, 22.43515912, 23.64679216, 33.40316974, 22.40547942,
       20.28211069, 25.2413554 , 31.47695469, 33.39153046, 28.43793741,
        8.541879  ,  4.85267978, 12.42580604, 20.41598522, 36.05885172,
       33.43770529, 15.81380686,  3.26964909, 33.70613701, 21.80595258,
       19.16226992, 26.12924528, 18.61875414, 17.76686204, 11.01275111,
       32.47158925, 24.70737227, 19.49374868, 19.3662591 , 11.5366082 ,
       28.982763  , 21.74478698, 32.57522994])